name: Compile LaTeX to PDF

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install TeXLive
        run: sudo apt-get install -y texlive texlive-latex-extra texlive-fonts-recommended texlive-latex-recommended

      - name: Compile TeX to PDF
        run: |
          pdflatex -interaction=nonstopmode -halt-on-error -output-directory=output main.tex

      - name: Upload generated PDF
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: output/main.pdf
