name: Compile Resume LaTeX to PDF

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Show directory structure (debugging)
        run: ls -R

      - name: Install TeXLive
        run: sudo apt-get install -y texlive texlive-latex-extra texlive-fonts-recommended texlive-latex-recommended

      - name: Compile Resume to PDF
        run: |
          cd me/resume/resume_scripts || exit 1
          ls -la
          pdflatex -interaction=nonstopmode -halt-on-error resume_english.tex

      - name: Upload generated PDF
        uses: actions/upload-artifact@v4
        with:
          name: Resume PDF
          path: me/resume/resume_scripts/resume_english.pdf
